/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author ikram
 */
public class MainGUI extends javax.swing.JFrame {
private BloodTestScheduler scheduler;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        scheduler = new BloodTestScheduler(); // Initialize in the constructor
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPNL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        GPDetailLBL = new javax.swing.JLabel();
        GPDetailTF = new javax.swing.JTextField();
        ageLBL = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        priorityLBL = new javax.swing.JLabel();
        priorityComboBox = new javax.swing.JComboBox<>();
        hospitalLBL = new javax.swing.JLabel();
        hospitalCheckBox = new javax.swing.JCheckBox();
        addPatientBTN = new javax.swing.JButton();
        getNextBTN = new javax.swing.JButton();
        addNoShowBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 18, 18));

        mainPNL.setBackground(new java.awt.Color(65, 15, 15));

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Blood Test Scheduler");

        nameLBL.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL.setText("Name:");

        nameTF.setBackground(new java.awt.Color(51, 51, 51));
        nameTF.setForeground(new java.awt.Color(255, 255, 255));

        GPDetailLBL.setForeground(new java.awt.Color(255, 255, 255));
        GPDetailLBL.setText("GP Details:");

        GPDetailTF.setBackground(new java.awt.Color(51, 51, 51));
        GPDetailTF.setForeground(new java.awt.Color(255, 255, 255));

        ageLBL.setForeground(new java.awt.Color(255, 255, 255));
        ageLBL.setText("Age:");

        ageTF.setBackground(new java.awt.Color(51, 51, 51));
        ageTF.setForeground(new java.awt.Color(255, 255, 255));

        priorityLBL.setForeground(new java.awt.Color(255, 255, 255));
        priorityLBL.setText("Priority:");

        priorityComboBox.setBackground(new java.awt.Color(255, 255, 255));
        priorityComboBox.setForeground(new java.awt.Color(0, 0, 0));
        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Medium", "Low" }));

        hospitalLBL.setForeground(new java.awt.Color(255, 255, 255));
        hospitalLBL.setText("From Hospital:");

        hospitalCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        hospitalCheckBox.setForeground(new java.awt.Color(255, 255, 255));

        addPatientBTN.setBackground(new java.awt.Color(51, 51, 51));
        addPatientBTN.setForeground(new java.awt.Color(255, 255, 255));
        addPatientBTN.setText("Add Patient");
        addPatientBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBTNActionPerformed(evt);
            }
        });

        getNextBTN.setBackground(new java.awt.Color(51, 51, 51));
        getNextBTN.setForeground(new java.awt.Color(255, 255, 255));
        getNextBTN.setText("Get Next Patient");
        getNextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNextBTNActionPerformed(evt);
            }
        });

        addNoShowBTN.setBackground(new java.awt.Color(51, 51, 51));
        addNoShowBTN.setForeground(new java.awt.Color(255, 255, 255));
        addNoShowBTN.setText("Add No-Show");
        addNoShowBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoShowBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPNLLayout = new javax.swing.GroupLayout(mainPNL);
        mainPNL.setLayout(mainPNLLayout);
        mainPNLLayout.setHorizontalGroup(
            mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(nameLBL)
                        .addGap(83, 83, 83)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPNLLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GPDetailLBL)
                                    .addComponent(hospitalLBL))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPNLLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageLBL)
                                    .addComponent(priorityLBL))
                                .addGap(83, 83, 83)))
                        .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospitalCheckBox)
                            .addComponent(GPDetailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ageTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priorityComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addPatientBTN)
                .addGap(43, 43, 43)
                .addComponent(getNextBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(addNoShowBTN)
                .addGap(26, 26, 26))
        );
        mainPNLLayout.setVerticalGroup(
            mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(31, 31, 31)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLBL))
                .addGap(43, 43, 43)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityLBL))
                .addGap(54, 54, 54)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLBL))
                .addGap(58, 58, 58)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPDetailLBL)
                    .addComponent(GPDetailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hospitalLBL)
                    .addComponent(hospitalCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientBTN)
                    .addComponent(getNextBTN)
                    .addComponent(addNoShowBTN))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBTNActionPerformed
        // TODO add your handling code here:
        // Get input values
        String name = nameTF.getText();
        String priority = (String) priorityComboBox.getSelectedItem();
        int age = Integer.parseInt(ageTF.getText());
        String gpDetails = GPDetailTF.getText();
        boolean fromHospital = hospitalCheckBox.isSelected();

        // Create a new Patient object
        Patient patient = new Patient(name, priority, age, gpDetails, fromHospital);

        // Add the patient to the scheduler
        scheduler.addPatient(patient);

        // Show confirmation message
        JOptionPane.showMessageDialog(rootPane, "Patient added: " + name + "\n");

        // Reset the input fields
        nameTF.setText(""); // Clear the name text field
        priorityComboBox.setSelectedItem("Urgent"); // Reset combo box to "Urgent"
        ageTF.setText(""); // Clear the age text field
        GPDetailTF.setText(""); // Clear the GP details text field
        hospitalCheckBox.setSelected(false); // Uncheck the checkbox
    }//GEN-LAST:event_addPatientBTNActionPerformed

    private void getNextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNextBTNActionPerformed
        // TODO add your handling code here:
        // Get the next patient from the scheduler
        Patient nextPatient = scheduler.getNextPatient();

        if (nextPatient != null) {
            // Display the patient's details
            String message = "Next Patient:\n"
                    + "Name: " + nextPatient.getName() + "\n"
                    + "Priority: " + nextPatient.getPriority() + "\n"
                    + "Age: " + nextPatient.getAge() + "\n"
                    + "GP Details: " + nextPatient.getGpDetails() + "\n"
                    + "From Hospital: " + (nextPatient.isFromHospital() ? "Yes" : "No");
            JOptionPane.showMessageDialog(rootPane, message);
        } else {
            // If no patients are in the queue
            JOptionPane.showMessageDialog(rootPane, "No patients in the queue.");
        }
    }//GEN-LAST:event_getNextBTNActionPerformed

    private void addNoShowBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoShowBTNActionPerformed
        // TODO add your handling code here:
        // Get the next patient from the scheduler
        Patient nextPatient = scheduler.getNextPatient();

        if (nextPatient != null) {
            // Add the patient to the no-show stack
            scheduler.addNoShow(nextPatient);

            // Display the last 5 no-shows
            StringBuilder noShowsMessage = new StringBuilder("Last 5 No-Shows:\n");
            Stack<Patient> noShowStack = scheduler.getNoShowStack();
            for (Patient patient : noShowStack) {
                noShowsMessage.append("- ").append(patient.getName()).append("\n");
            }

            JOptionPane.showMessageDialog(rootPane, noShowsMessage.toString());
        } else {
            // If no patients are in the queue
            JOptionPane.showMessageDialog(rootPane, "No patients in the queue to mark as no-show.");
        }
    }//GEN-LAST:event_addNoShowBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GPDetailLBL;
    private javax.swing.JTextField GPDetailTF;
    private javax.swing.JButton addNoShowBTN;
    private javax.swing.JButton addPatientBTN;
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton getNextBTN;
    private javax.swing.JCheckBox hospitalCheckBox;
    private javax.swing.JLabel hospitalLBL;
    private javax.swing.JPanel mainPNL;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JComboBox<String> priorityComboBox;
    private javax.swing.JLabel priorityLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
